pretrained_base_model_path: "../Models/stable-diffusion-v1-5/"
pretrained_vae_path: "../Models/sd-vae-ft-mse"
image_encoder_path: "../Models/sd-image-variations-diffusers/image_encoder"
denoising_unet_path: "../Models/AnimateAnyone/denoising_unet.pth"
reference_unet_path: "../Models/AnimateAnyone/reference_unet.pth"
pose_guider_path: "../Models/AnimateAnyone/pose_guider.pth"
motion_module_path: "../Models/AnimateAnyone/motion_module.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "./configs/inference/ref_images/anyone-2.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
    - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  "./configs/inference/ref_images/anyone-10.png":
    - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  "./configs/inference/ref_images/anyone-11.png":
    - "./configs/inference/pose_videos/anyone-video-1_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
  "./configs/inference/ref_images/anyone-3.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4"
    - "./configs/inference/pose_videos/anyone-video-5_kps.mp4"
  "./configs/inference/ref_images/anyone-5.png":
    - "./configs/inference/pose_videos/anyone-video-2_kps.mp4" 
