pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./pretrained_weights/denoising_unet.pth"
reference_unet_path: "./pretrained_weights/reference_unet.pth"
pose_guider_path: "./pretrained_weights/pose_guider.pth"
motion_module_path: "./pretrained_weights/motion_module.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "/home/itec/emanuele/Datasets/djokovic_federer/crops/012/id1/00000.png":
    - "/home/itec/emanuele/Datasets/djokovic_federer/dwpose_videos/012/id1_kps.mp4"
