data:
  train_bs: 1
  train_width: 512
  train_height: 512
  meta_paths:
    - "/home/itec/emanuele/Datasets/djokovic_federer/meta.json"
  sample_rate: 4
  n_sample_frames: 16

solver:
  gradient_accumulation_steps: 4
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: True
  max_train_steps: 3000
  max_grad_norm: 1.0
  # lr - lower for fine-tuning
  learning_rate: 5.0e-6
  scale_lr: False
  lr_warmup_steps: 100
  lr_scheduler: 'cosine'

  # optimizer
  use_8bit_adam: False
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 500

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: './pretrained_weights/stable-diffusion-v1-5'
vae_model_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/image_encoder'
mm_path: './pretrained_weights/motion_module.pth'

# Stage 1 fine-tuned weights will be loaded from here
stage1_ckpt_dir: './exp_output/finetune_stage1'
# Will be set dynamically to the latest checkpoint

weight_dtype: 'fp16'
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True

seed: 42
resume_from_checkpoint: ''
checkpointing_steps: 1000
exp_name: 'finetune_stage2'
output_dir: './exp_output'
